# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.1.3"

package:
  name: node-red
  version: ${{ version }}

source:
  - url: https://registry.npmjs.org/node-red/-/node-red-${{ version }}.tgz
    sha256: 88b21a94a765bd436e73d2cc3b966140835a48fe2720905a33c48248b7235d2f

build:
  number: 0
  script: build.nu
  # noarch: generic # has binaries on macos, so not 'noarch'

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
    - nushell
  run:
    - nodejs

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        - if: not win
          then:
            - share/node-red/service.yaml
          else:
            - Library\share\node-red\service.yaml
  # Test 2: Functional tests
  - script:
      content:
        - node-red --help

about:
  homepage: https://nodered.org
  summary: Low-code programming for event-driven applications
  description: |
    Node-RED's goal is to enable anyone to build applications that collect,
      transform and visualize their data;
      building flows that can automate their world.
      Its low-code nature makes it accessible to users of any background,
      whether for home automation,
      industrial control systems or anything in between.
  license: Apache-2.0
  license_file:
    - LICENSE
  documentation: https://nodered.org/docs/
  repository: https://github.com/node-red/node-red

extra:
  recipe-maintainers:
    - phreed
